name: ThisLogMustDie
main: fr.areku.tlmd.Main
author: ThisIsAreku
website: http://alexoft.x10.mx/
version: 0.5
description: Format your console !
load: STARTUP

commands:
    tlmd:
        description: ThisLogMustDie - Main command
        usage: /tlmd help