name: ThisLogMustDie
main: alexoft.tlmd.Main
author: ThisIsAreku
website: http://alexoft.x10.mx/
version: 0.4.4
description: Format your console !
load: STARTUP

commands:
    tlmd:
        description: ThisLogMustDie - Main command
        usage: /tlmd help